services:
  db:
    image: postgres:15.1-alpine
    container_name: "kotgres-db"
    environment:
      - POSTGRES_USER=kotgres
      - POSTGRES_PASSWORD=kotgres123
      - POSTGRES_DB=kotgres
    ports:
      - '54329:5432'
    volumes:
      - ./tests/src/test/resources/migrations:/docker-entrypoint-initdb.d/
