CREATE TABLE users_with_id
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text,
    age          int,
    date_created timestamp
);

CREATE TABLE users_with_default_date_updated
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text,
    age          int,
    date_updated timestamp DEFAULT to_timestamp(0)
);

CREATE TABLE users_with_default_date_updated_now
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text,
    age          int,
    date_updated timestamp DEFAULT now()
);

CREATE TABLE users_with_id_always_generated
(
    id   int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE countries
(
    code         text PRIMARY KEY,
    full_name    text,
    date_created timestamp
);

CREATE TABLE countries_with_unique
(
    code         text PRIMARY KEY,
    full_name    text UNIQUE,
    date_created timestamp
);

CREATE TABLE column_with_changed_name
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correct_name int
);

CREATE TABLE primary_key_with_different_name
(
    id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    int int
);
