CREATE TABLE vehicle_no_enum
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type text
);

CREATE TYPE vehicle_type AS ENUM ('car', 'motorbike');

CREATE TABLE vehicle_with_enum
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type vehicle_type
);
