CREATE TABLE table_with_json
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content jsonb not null
);


CREATE TABLE table_with_jsonb
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content jsonb not null
);
