CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users_with_uuid_pkey
(
    uuid uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    name text
);

CREATE TABLE users_with_generated_uuid
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid DEFAULT uuid_generate_v4(),
    name text
);
